export const ProfileDescription = (
    <>
        I am a software developer interested in Full Stack Mobile & Web
        Development and Artificial Intelligence/Machine Learning!
    </>
);

export const projects = [
    {
        title: "Shelf Stability System",
        description: (
            <>
                Shelf Stability System is a web app I developed in a team of 3
                for my ECE Senior Design class. The system is designed to
                streamline the conplexities of managing food shelf life
                experiments. It presents a user-friendly interface for data
                entry and visualization, single sign-on (SSO) login via Duke
                OAuth, and an admin dashboard for managing users. The system
                also features additional functionalities such as Excel data
                exports, reliable database backups, email reminders for upcoming
                experiment assays, and QR codes for assay labels.
            </>
        ),
        image: "images/shelf-stability-system.png",
        tags: ["Next.js", "Prisma", "PostgreSQL", "Vercel"],
        source: "https://github.com/richardd3ng/Shelf-Stability-System",
        visit: "https://shelf-stability-system.colab.duke.edu",
        id: 0,
    },
    {
        title: "Repo Amigo",
        description: (
            <>
                Repo Amigo is a chatbot web app I developed using Python that
                delivers a user-friendly interface for Github repository
                exploration. Users can ask questions about a selected
                repository, and receive answers generated by OpenAI's Large
                Language Models (LLMs) such as GPT-3.5-Turbo. The system employs
                persistent storage by caching document chunk embeddings in
                vector databases, ensuring that fetched repository data is
                retained across user sessions for enhanced efficiency. Moreover,
                the web app integrates GitHub login functionality using OAuth2,
                allowing users to authenticate themselves effortlessly with
                their GitHub credentials.
            </>
        ),
        image: "images/repo-amigo.png",
        tags: ["OpenAI", "LangChain", "ChromaDB", "Streamlit"],
        source: "https://github.com/richardd3ng/Repo-Amigo",
        visit: "https://repo-amigo.streamlit.app",
        id: 1,
    },
    {
        title: "GAN Research Project",
        description: (
            <>
                A Generative Adversarial Network (GAN) is a type of AI model
                designed to generate new, realistic data by learning patterns
                from existing data. This research project creates 3 GAN variants
                for CIFAR-10 image generation and evaluates their strengths and
                limiations. The first GAN is a WGAN-GP that uses the Wasserstein
                Distance loss to address training stability and mode collapse
                issues. The second GAN is an AC-GAN that introduces an auxiliary
                classifier to generate labeled images. The third GAN is a hybrid
                "WAC-GAN-GP" combining the benefits of labeled data generation
                with training stability. Applying WAC-GAN-GP to CIFAR-10 is
                novel."
            </>
        ),
        image: "images/gan.png",
        tags: ["PyTorch", "Google CoLab"],
        source: "https://github.com/richardd3ng/GAN-project",
        visit: "https://drive.google.com/file/d/1YmP5rwYGW8qqQvK5N8Kp09dRA0kISU0Q/view?usp=sharing",
        id: 2,
    },
    {
        title: "Nscribe",
        description: (
            <>
                As a member of the Global Alliance for Medical Innovation {}
                <a href="https://harvardgami.org" style={{ color: "blue" }}>
                    (GAMI)
                </a>
                , I co-led a team of students to work with doctors and
                professors to develop ML models to detect Parkinson's and
                Alzheimer's Disease from patients' handwriting data. Nscribe is
                an iOS app currently on TestFlight designed to help medical
                professionals collect handwriting data from patients for
                neurodegenerative disease diagnosis purposes. The full paper
                detailing the ML analysis pipeline we developed is linked below
                in "More Info."
            </>
        ),
        image: "images/nscribe.png",
        tags: ["XCode", "SwiftUI"],
        source: "https://github.com/jaychandra3/DrawingApp",
        visit: "https://pubmed.ncbi.nlm.nih.gov/34679363",
        id: 3,
    },
    {
        title: "MusicMap",
        description: (
            <>
                MusicMap, a class project I worked on in a team of 6, is a
                mobile app that documents the songs played during road trips.
                The app allows users to revisit a catalog of all the songs
                played during the trip and see the specific locations associated
                with each song. A map screen displays the user’s current
                location and drops pins during song changes or image uploads.
                Users can also relive their memories by viewing video collages
                of their songs and images during past trips.
            </>
        ),
        image: "images/music-map.png",
        tags: ["MongoDB", "Express", "React Native", "Node"],
        source: "https://github.com/nyu12345/MusicMap",
        visit: "https://github.com/nyu12345/MusicMap",
        id: 4,
    },
];

export const TechnologiesDesription = (
    <>
        Through my experiences in classes, personal projects, extracurriculars,
        and internships, I've worked with a range of technologies across full
        stack development and machine learning.
    </>
);

export const AboutMeDescription = (
    <>
        Hi there! I graduated from Duke University in 2024 with degrees in
        Computer Science and Electrical/Computer Engineering. Although I've
        spent the last few years in North Carolina, I originally grew up in the
        Bay Area, where my interest in technology was sparked from an early age.
        Through my classes and extracurriculars, I've had the opportunity to
        work on a plethora of exciting projects, from developing mobile
        applications to applying novel ML solutions to ongoing problems. I've
        also gained valuable experience through internships at a variety of tech
        companies, where I've had the chance to collaborate with talented
        engineers and learn about the latest industry trends and practices. When
        I'm not coding, you can find me working out, jamming on my piano,
        experimenting with healthy recipes in the kitchen, or traveling to
        explore new places!
    </>
);

export const TimeLineData = [
    { year: 2020, text: "Started college at Duke!" },
    {
        year: 2021,
        text: "Worked as a SWE intern at Mi-Corporation (acquired by Ideagen)",
    },
    { year: 2022, text: "Worked as a SWE intern at Meta" },
    { year: 2023, text: "Worked as a SWE Intern at Roblox" },
    { year: 2024, text: "Graduated from Duke!" },
];
